name: Build and Deploy to Azure Web App

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/**'

env:
    AZURE_WEBAPP_NAME: 'FeedMng-ow7hoth4du2vq-app'
    AZURE_WEBAPP_PACKAGE_PATH: './dotnetcorewebapp'
    PROJECT_NAME: 'FeedbackManager.Web'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_NAME }}
    - name: Build
      run: dotnet build --no-restore ${{ env.PROJECT_NAME }}
    - name: Test
      run: dotnet test --no-build --verbosity normal ${{ env.PROJECT_NAME }}
    - name: Publish
      run: dotnet publish -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH}} ${{ env.PROJECT_NAME }}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: webapp
        path: dotnetcorewebapp
    
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.7
      with:
        name: webapp
        path: dotnetcorewebapp
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: Azure/webapps-deploy@v1
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './dotnetcorewebapp/'
